- name: Install docker & docker-compose
  package:
    name:
      - docker-ce
      - docker-compose

- name: Create docker settings directory
  file:
    name: "/etc/docker"
    mode: '0700'
    owner: root
    group: root
    state: directory

- name: Prepare docker daemon.json file
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: '0600'
    force: yes
  notify: Restart docker

- name: Start docker
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
