---
- name: Common setup
  hosts: mirrors_service
  tasks:

    - name: Set sources_root
      set_fact:
        sources_root: "{{ source_path }}"
      tags:
        always

    - name: Set config_root
      set_fact:
        config_root: "/etc/mirrors_service/{{ container_env_prefix }}"
      tags:
        always

    - import_role: name=common_setup
      tags:
        common_setup

    - import_role: name=deploy_files
      tags:
        sync

    - import_role: name=prepare_host
      tags:
        prepare_host
    - import_role: name=postgres
      tags:
        postgres
    - import_role: name=backend
      tags:
        backend
