---
- name: Remove old docker image
  docker_image:
    name: "python38-uwsgi"
    state: absent


- name: Build docker image
  docker_image:
    name: "python38-uwsgi"
    build:
      path: "{{ source_path }}/ci/"
      pull: yes
      network: host
    source: build

- name: Set facts for docker container with backend
  set_fact:
    uwsgi_processes: "{{ (uwsgi_processes is defined) | ternary(uwsgi_processes, 4) }}"
    deploy_env: "{{ deploy_environment | default('Development') }}"
    test_ip_addr: "{{ test_ip_address | default('') }}"
    sentry_disabled: "{{ (deploy_environment is defined and deploy_environment == 'Production') | ternary('False', 'True') }}"
    published_ports: "{{ (deploy_environment is defined and deploy_environment == 'Production') | ternary(['127.0.0.1', backend_port] | join(':'), backend_port) }}:3031"


- name: Up the container from docker image
  docker_container:
    name: "{{ container_env_prefix }}_backend"
    image: "python38-uwsgi"
    state: started
    restart: no
    restart_policy: unless-stopped
    env:
      UWSGI_PROCESSES: "{{ uwsgi_processes | string }}"
      SENTRY_DSN: "{{ sentry_dsn | string }}"
      PYTHONPATH: "/src/app"
      DEPLOY_ENVIRONMENT: "{{ deploy_env | string }}"
      TEST_IP_ADDRESS: "{{ test_ip_addr | string }}"
      AUTH_KEY: "{{ auth_key | string }}"
      SENTRY_DISABLED: "{{ sentry_disabled | string }}"
    published_ports:
      - "{{ published_ports }}"
    mounts:
      - source: "{{ source_path }}/src/backend"
        target: "/src/app"
        read_only: yes
        type: bind
      - source: "{{ config_root }}/mirrors"
        target: "/mirrors"
        read_only: no
        type: bind
      - source: "{{ config_root }}/sqlite"
        target: "/sqlite"
        read_only: no
        type: bind
    log_driver: "json-file"
    log_options:
      max-size: "200m"
      max-file: "5"
