---
- name: Prepare backend env files
  template:
    src: "{{ item.src }}"
    dest: "{{ config_root }}/{{ item.dest }}"
    owner: root
    group: root
    mode: '0600'
    force: '{{ item.force }}'
  with_items:
      - {dest: '{{ env_file }}', force: yes, src: 'env.j2'}
