- name: Install certbot package
  package:
    name:
      - certbot

- name: Create webroot for certs
  file:
      name: /etc/delivery/nginx/acme/
      state: directory

- name: Obtain certificate first time
  shell: certbot certonly -w=/etc/delivery/nginx/acme/ --standalone \
    {% if letsencrypt_production != 'true' %} --test-cert {% endif %} \
    -m {{ letsencrypt_notify_email }} --agree-tos -d {{ backend_public_domain }} -n
  args:
    creates: /etc/letsencrypt/live/{{ backend_public_domain }}

- name: Prepare certbot cron job
  template:
    src: "certbot.cron"
    dest: "/etc/cron.d/certbot"
    owner: root
    group: root
    mode: '0600'
    force: yes
