version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: python38-uwsgi
    networks:
      - backend
    restart: unless-stopped
    environment:
      UWSGI_PROCESSES: "${UWSGI_PROCESSES}"
      SENTRY_DSN: "${SENTRY_DSN}"
      PYTHONPATH: "/src/app"
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      TEST_IP_ADDRESS: "${TEST_IP_ADDRESS}"
      AUTH_KEY: "${AUTH_KEY}"
      SQLITE_PATH: "${SQLITE_PATH}"
    volumes:
      - ../src/backend:/src/app:ro
      - ${CONFIGS_DIR}/mirrors:/mirrors
      - ${CONFIGS_DIR}/sqlite:/sqlite
    ports:
      - ${BACKEND_PORT}:3031
    logging:
      options:
        max-size: "200m"
        max-file: "5"

networks:
  backend:
  public:
    driver: bridge
