- name: Set path to env file
  set_fact:
    DOCKER_BASH_ENV_FILE: "{{ config_root + '/env' }}"

- name: Restart "{{ service }}" container
  shell: "source {{ DOCKER_BASH_ENV_FILE }} \
    && docker-compose -f {{ compose_file }} up -d --build --no-deps \
    --force-recreate --remove-orphans {{ service }}"
  args:
    chdir: "{{ sources_root }}/ci/"
  environment:
    COMPOSE_PROJECT_NAME: "{{ container_env_prefix }}"
    CONFIGS_DIR: "{{ config_root }}"
  retries: 10
  delay: 1
  register: result
  until: (result.get('rc', -1) == 0) or ('i/o timeout' not in result.get('stderr', ''))
